### ISSUE TITLE
Update Rawrbot to run on Ruby 2.x

### ISSUE THREAD

**Issue by pfaffle** [pfaffle/Rawrbot#11]
Ruby 1.9 is getting old. Test Rawrbot in Ruby 2.1 and update any code that doesn't work with it.

**Comment by pfaffle** [comment]
Main thing that's holding me back here is that CTRL+Cing the bot on newer Ruby throws the following exception:

```
^C/home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/message_queue.rb:46:in `synchronize': can't be called from trap context (ThreadError)
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/message_queue.rb:46:in `queue'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/irc.rb:286:in `send'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/bot.rb:229:in `quit'
        from ./rawrbot.rb:53:in `block in <main>'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/irc.rb:221:in `call'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/irc.rb:221:in `join'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/irc.rb:221:in `start'
        from /home/pfaffle/.rvm/gems/ruby-2.2.3/gems/cinch-2.2.4/lib/cinch/bot.rb:273:in `start'
        from ./rawrbot.rb:56:in `<main>'
```

I haven't figured out what to do about this yet.
